name: 'Build'

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true

      #
      # Build using CMake
      #
    - name: Build using CMake
      run: |
        mkdir build && cd build
        cmake ..
        cmake --build . -j8

    - name: Run tests
      run: |
        cmake --build . --target=test

