name: Create release and update website

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  website:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Add version to doxyfile
      run: |
        echo "PROJECT_NUMBER = $(git describe --tags --abbrev=0)" >> docs/Doxyfile

    - name: Run Doxygen
      uses: mattnotmitt/doxygen-action@v1.9.4
      with:
        doxyfile-path: 'docs/Doxyfile'

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./doc

  publish:
    name: Create release and upload files
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Create deb package
      run: |
        mkdir build && cd build
        cmake .. -DBUILD_TEST=OFF -DBUILD_DOC=OFF
        make package -j4
        cd ..

    - name: Find changes
      id: files
      run: |
        PREVIOS="$(git tag --sort=creatordate | tail -n 2 | head -n1)"
        wget https://raw.githubusercontent.com/tim-gromeyer/html2md/$PREVIOS/CHANGELOG.md -O OLD.md
        echo "CHANGES<<EOF" >> $GITHUB_ENV
        echo "$(grep -Fvxf OLD.md CHANGELOG.md | tail -n +2)" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

        echo "FILES<<EOF" >> $GITHUB_ENV
        find /home/runner/work/html2md/html2md/build -name "*.deb" -type f >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        generate_release_notes: true
        body: ${{ env.CHANGES }}
        files: ${{ env.FILES }}

