name: Update website

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2

    - name: Run Doxygen
      uses: mattnotmitt/doxygen-action@v1.9.4
      with:
        doxyfile-path: 'docs/Doxyfile'

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./doc

