name: Doxygen Action

on:
  push:
    branches-ignore:
      - master
    tags-ignore:
      - '*'
  
jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
        
    - name: Install dot
      run: |
        sudo apt-get update
        sudo apt-get install graphviz -y

    - name: Run Doxygen
      uses: mattnotmitt/doxygen-action@v1.9.4
      with:
        doxyfile-path: 'docs/Doxygen'

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./doc

